# Generated by Django 3.0.6 on 2020-05-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacao',
            old_name='data_receita',
            new_name='data_publicacao',
        ),
        migrations.RenameField(
            model_name='publicacao',
            old_name='foto_receita',
            new_name='foto_publicacao',
        ),
    ]
